# for other versions of docker-compose, check the official documentation
version: "3.8"

services:
  db:
    image: postgres:15-bookworm # Debian Bookworm official image for PostgreSQL - https://wiki.debian.org/DebianBookworm
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: machine
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # Verificar se o banco de dados está pronto
      interval: 10s # Verificar a cada 10 segundos
      retries: 5 # Tentar 5 vezes antes de falhar

  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3333:3333"
    depends_on:
      - db
    restart: always # Reiniciar sempre se houver falha
